<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1olg6r\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1olg6r/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM1olg6r.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM1olg6r\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM1olg6r\appProdProjectContainer([
    'container.build_hash' => 'M1olg6r',
    'container.build_id' => '6c6c6de4',
    'container.build_time' => 1697469383,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1olg6r');
